import { useState } from 'react';
import { capabilities } from '../data/capabilities';
import { projects } from '../data/portfolio';
import { Arrow } from '../components/Arrow';

export function Capabilities({ onSelect }: { onSelect: () => void }) {
  const [selected, setSelected] = useState(2);
  const capability = capabilities[selected];
  return <section id="capacidades" className="capabilities-section" aria-labelledby="capabilities-title"><div className="section-heading"><div><span className="section-index">02 / SISTEMA DE CAPACIDADES</span><h2 id="capabilities-title">Una necesidad.<br /><span>Muchas conexiones.</span></h2></div><p>Empieza por lo que quieres resolver.<br />Conectamos las piezas para hacerlo posible.</p></div><div className="capability-system"><div className="capability-selector" role="group" aria-label="Selecciona tu necesidad">{capabilities.map((item, index) => <button key={item.code} aria-pressed={selected === index} aria-controls="capability-output" onClick={() => {setSelected(index); onSelect();}}><span className="capability-number">0{index + 1}</span><span><strong>{item.short}</strong><small>{item.name}</small></span><span className="connection-point" aria-hidden="true">{selected === index ? '−' : '+'}</span></button>)}</div><div id="capability-output" className="capability-output" aria-live="polite"><div className="capability-output-top"><span><i className="status-dot" /> CONEXIÓN ESTABLECIDA</span><span>{capability.code} / 0{selected + 1}</span></div><h3>{capability.title}</h3><p>{capability.problem}</p><div className="parts-flow" aria-label="Piezas del sistema">{capability.parts.map((part, index) => <span key={part}><small>0{index + 1}</small>{part}</span>)}</div><dl><div><dt>EL PRODUCTO</dt><dd>{capability.product}</dd></div><div><dt>LO QUE RECIBES</dt><dd>{capability.result}</dd></div></dl><div className="related-projects"><span className="micro-label">EXPLORA REFERENCIAS RELACIONADAS</span><div>{capability.related.map(id => { const project = projects.find(item => item.id === id)!; return <a href={`#proyecto-${id}`} key={id}>{project.name}<Arrow diagonal /></a>; })}</div>{capability.note && <small>{capability.note}</small>}</div></div></div><noscript><p>También desarrollamos sistemas personalizados, aplicaciones móviles, ecommerce y plataformas empresariales. Escríbenos para explorar qué necesita tu proyecto.</p></noscript></section>;
}
