import { useState } from 'react';

const steps = [
  ['Entender', 'Escuchamos antes de escribir código.', 'Definimos el problema, las personas que usarán el producto y lo que debe lograr. El punto de partida es una necesidad real.', 'Un alcance compartido'],
  ['Diseñar', 'La idea toma forma.', 'Convertimos los recorridos en interfaces y prototipos. Revisamos contigo cómo se verá y cómo se usará.', 'Un prototipo para conversar'],
  ['Construir', 'Cada pieza encuentra su lugar.', 'Desarrollamos las funciones acordadas, conectamos los componentes y cuidamos la experiencia en distintos dispositivos.', 'Un producto funcional'],
  ['Validar', 'Lo probamos en el mundo de las personas.', 'Revisamos los flujos, la accesibilidad y el rendimiento. Corregimos antes de dar el siguiente paso.', 'Una versión verificada'],
  ['Lanzar y evolucionar', 'El lanzamiento es un nuevo comienzo.', 'Preparamos la entrega y definimos cómo acompañar la siguiente etapa de tu producto.', 'Una base para seguir creciendo'],
];

export function Process({ onSelect }: { onSelect: (index: number) => void }) {
  const [selected, setSelected] = useState(0);
  return <section id="proceso" className="process-section" aria-labelledby="process-title"><div className="section-heading"><div><span className="section-index">03 / DEL IMPULSO AL PRODUCTO</span><h2 id="process-title">Nada al azar.<br /><span>Todo conectado.</span></h2></div><p>Construir bien empieza por entender bien.<br />Así avanzamos, contigo.</p></div><div className="process-track" role="group" aria-label="Etapas del desarrollo">{steps.map((step, index) => <button key={step[0]} aria-pressed={index === selected} aria-controls="process-detail" className={index <= selected ? 'passed' : ''} onClick={() => {setSelected(index); onSelect(Math.min(3, index));}}><span className="process-point"><i /></span><span className="process-step-label">{step[0]}</span></button>)}</div><div id="process-detail" className="process-detail" aria-live="polite"><span className="process-big-number">0{selected + 1}<small>/ 05</small></span><div><h3>{steps[selected][1]}</h3><p>{steps[selected][2]}</p></div><span className="process-deliverable"><span className="micro-label">CADA PASO DEJA ALGO CONCRETO</span><strong>↳ {steps[selected][3]}</strong></span></div><div className="principles"><p>No construimos por construir.<br /><strong>Construimos para que tenga sentido.</strong></p><div><span>01</span><h3>Tu realidad primero</h3><p>La solución se adapta al negocio, a las personas y a sus necesidades.</p></div><div><span>02</span><h3>Claridad en cada paso</h3><p>Alcance definido, decisiones compartidas y entregables que puedes revisar.</p></div><div><span>03</span><h3>Calidad que se usa</h3><p>Funcionalidad, accesibilidad y rendimiento como parte del producto.</p></div></div><noscript><p>Entender → Diseñar → Construir → Validar → Lanzar y evolucionar. Cada etapa deja un entregable concreto que revisamos contigo.</p></noscript></section>;
}
